/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9ukMvtEI2EB
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@/components/ui/card"
import Link from "next/link"

export function VisitCard() {
  return (
    <Card className="w-full max-w-md bg-gradient-to-br from-[#1e293b] to-[#0f172a] text-white p-6 rounded-lg shadow-lg">
      <div className="space-y-4">
        <h3 className="text-2xl font-bold">Discover the Power of Dark Mode</h3>
        <p className="text-muted-foreground">
          Immerse yourself in a sleek and sophisticated interface that reduces eye strain and enhances productivity.
          Experience the future of digital design with our dark-themed card.
        </p>
        <Link
          href="#"
          className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-6 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
          prefetch={false}
        >
          Learn More
        </Link>
      </div>
    </Card>
  )
}
